# Dependencies
markdown:         kramdown
highlighter:      rouge


# Setup
title:            Khang Tong
tagline:          Mathematician and Classical Guitarist
description:      'Math, music, and language learning'
url:              https://www.khangtong.com
# baseurl:          '/hydeout'
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Khang Tong'

social:
  name: Khang Tong
  links:
    - https://www.youtube.com/user/hophopkangaroo
    - https://www.instagram.com/khang.aroo
    - https://www.linkedin.com/in/khangtong
  


paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.

#Enable Google Analytics
google_analytics: G-T5NH9Y9540